data:
  path: null
  max_length: null
  batch_size: 128

critic:
  model_name: null
  tokenizer_name: ${critic.model_name}
  gradient_checkpointing: true
  ddp_size: 1
  tp_size: 1
  sp_size: 1
  max_length_per_device: null
  lr: 1e-5
  weight_decay: 1e-2
  max_grad_norm: 1.0
  warmup_ratio: 0.1
  offload_optimizer: true

trainer:
  project: null
  experiment_name: null
  load_ckpt_from_dir: null
  n_epochs: 1
  save_dir: ckpts/${trainer.experiment_name}
  save_freq: null
  disable_wandb: false